---
title: "Fooof MRS Paper"
author: "Shane McKeon"
date: "2023-08-31"
geometry: margin = 1in
output:
  pdf_document: 
    toc: yes
    toc_depth: 4
    fig_caption: yes
  latex_engine: xelatex
---

```{r load-libraries, message=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, dev='png', dpi=150, fig.height=4, fig.width = 6, fig.path='/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Aperiodic_MRS_Development/Results/paper_figs/')
```


```{r, echo= FALSE, message = FALSE, warning = FALSE}

library(LNCDR)
library(data.table)
library(dplyr)
require(knitr)
library(ggplot2)
library(e1071)
library(caret)
library(ggplot2)
library(readxl)
library(Hmisc)
library(lmerTest)
library(corrplot)
library(RColorBrewer)
library(data.table)
library(cowplot)
library(mgcv)
library(tidyr)

```

```{r, echo= FALSE, message = FALSE, warning = FALSE}


fooofMRSbehavior <- read.csv('/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Aperiodic_MRS_Development/Results/allSubjectsDLPFCfooofMRSBehaviorMeasures_20231031.csv')
fooofLong <- read.csv('/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Aperiodic_MRS_Development/Results/allSubjectsDLPFCfooofMeasures_20231031.csv')
MRSlong <- read.csv("/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Aperiodic_MRS_Development/Results/allSubjectsDLPFCMRSMeasures_20231031.csv")
fooofMRS<- read.csv("/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Aperiodic_MRS_Development/Results/allSubjectsDLPFCfooofMRSMeasures_20231031.csv")
behav <- read.csv("/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Aperiodic_MRS_Development/Results/allSubjectsBehavior.csv")

```

# FOOOF Plots 
```{r fooofPlots, echo= FALSE, message = FALSE, warning = FALSE, fig.height=8, fig.width = 20}
fooofLong <- fooofLong %>% mutate(ageGroup = cut(age, c(0,17,23,Inf), labels = c('10-16','17-22','23-30')))

# Exponent vs age
exp <- lunaize(ggplot(data = fooofLong, 
                      aes(x = age, y = Exponent)) + 
                 geom_line(aes(group=interaction(luna,Region,Condition), linetype = Condition, shape =Region), alpha = 0.2) + 
                 geom_point(aes(shape=Region, color=ageGroup), size=2.5,alpha=.8) + 
                 geom_smooth(aes(group = 1, color = "black"), method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.4,size=2)) + xlab("Age") + ylab("Exponent") +
  geom_text(
    aes(x = 35, y = 1.2, label = "***"),size = 10) +
 scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))+
  theme(text = element_text(size = 25), legend.text=element_text(size=15),
        legend.position = c(0.7, 1), legend.text.align = 0,legend.box = "horizontal", legend.key.width = unit(2, "line"), aspect.ratio = 1,
        axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2), plot.margin = margin(0.5,0.5,0.5,0.5,"cm")) +
  scale_shape_manual(values = c(16, 17), labels = c("L DLPFC", "R DLPFC")) + 
  scale_linetype_manual(values = c(1,2), labels = c("Eyes Closed", "Eyes Open")) + 
  guides(shape = guide_legend(title = "Region", override.aes = list(size = 2,fill=NA,alpha=0.8), title.theme = element_text(size = 15)), linetype = guide_legend(title = "Condition",override.aes = list(linewidth = 1,color ="black", alpha=0.8), title.theme = element_text(size = 15)), color="none", size ="none")



# Offset vs age
off <- lunaize(ggplot(data = fooofLong, 
                      aes(x = age, y = Offset)) + 
                 geom_line(aes(group=interaction(luna,Region,Condition), linetype = Condition, shape =Region), alpha = 0.2) + 
                 geom_point(aes(shape=Region, color=ageGroup), size =2.5,alpha=.8) + 
                 geom_smooth(aes(group = 1, color="black"), method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.4,size=2)) + 
  xlab("Age") + ylab("Offset") + 
   scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))+
  geom_text(aes(x = 35, y = .6, label = "***"), size = 10) +
  theme(text = element_text(size = 25), plot.margin = margin(0.5,0.5,0.5,0.5,"cm"),
        legend.position = "none", legend.text.align = 0, legend.key.width = unit(2, "line"), aspect.ratio = 1,
        axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2)) 


psd <- read.csv('/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Aperiodic_MRS_Development/Results/PSDtable.csv')
freqs <- read.csv('/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Aperiodic_MRS_Development/Results/freqs.csv')

psd_long <- pivot_longer(psd, cols = PSDs_1:PSDs_257, names_to = 'f_name', values_to = 'Power') %>%
  separate(f_name, c('junk', 'f_idx'), "_", convert = TRUE) %>% select(-junk) %>%
  rename(age = eeg_age) %>%
  mutate(ageGroup = cut(age, c(0,17,23,Inf), labels = c('10-16','17-22','23-30'))) %>% cbind(., freqs)

psd_long_filtered <- psd_long %>% filter(!is.infinite(Power) & Power > 0 & !is.na(Power)) %>%
  group_by(ageGroup, f_idx) %>% 
  mutate(z = scale(Power)[,1],
         f = freqs,
         Band = cut(freqs, c(1,4,8,13,30,48), labels = c('Delta (1-4 Hz)', 'Theta (4-8 Hz)', 'Alpha (8-13 Hz)', 'Beta (13-30 Hz)', 'Gamma (30-48 Hz)'))
  ) %>%
  ungroup() %>%
  filter(abs(z) < 3)


  
psd_byGroup <- psd_long_filtered %>% filter(!is.infinite(Power) & Power > 0 & !is.na(Power)) %>%
  group_by(ageGroup, freqs) %>% 
  dplyr::summarize(meanPower = mean(Power, na.rm=T), 
            medPower = median(Power, na.rm=T),
            power_sd = sd(Power, na.rm=T),
            n = n()) %>%
  mutate(f = freqs,
         se = power_sd / sqrt(n))
  
psdGraph<- lunaize(ggplot(data = psd_byGroup %>% filter(f>=4 & f<39) %>% arrange(f) %>% mutate(Age = ageGroup), 
               aes(x = f, y = meanPower, color = Age)) +
  geom_line() +
  geom_ribbon(aes(ymin=meanPower-se, ymax=meanPower+se, fill=Age), alpha=0.5, linewidth=0) +
  scale_y_log10() +
  labs(x = 'Frequency (Hz)', y = 'Power')) + scale_fill_manual(values=c("#E3B23C", "plum4", "#2E041F"))+scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F"))+
  theme(text = element_text(size = 25),legend.position=c(0.8, 0.8),
        axis.text.x = element_text(margin = margin(t = 0, r = 0, b = -20, l = 0)),
        axis.text.y = element_text(margin = margin(t = 0, r = 0, b = 0, l = -25)), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2),plot.margin = margin(0.5,0.5,0.5,0.5,"cm"))


lunaize(ggplot(data = psd_byGroup %>% filter(f>=4 & f<50) %>% arrange(f) %>% mutate(Age = ageGroup), 
               aes(x = f, y = meanPower, color = Age)) +
  geom_line() +
  geom_ribbon(aes(ymin=meanPower-se, ymax=meanPower+se, fill=Age), alpha=0.5, linewidth=0) +
  scale_y_log10() +
  labs(x = 'Frequency (Hz)', y = 'Power')) + scale_fill_manual(values=c("#E3B23C", "plum4", "#2E041F"))+scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F"))+
  theme(text = element_text(size = 25),legend.position=c(0.8, 0.8),
        axis.text.x = element_text(margin = margin(t = 0, r = 0, b = -20, l = 0)),
        axis.text.y = element_text(margin = margin(t = 0, r = 0, b = 0, l = -25)), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2),plot.margin = margin(0.5,0.5,0.5,0.5,"cm")) + facet_wrap(~Age)


  plot_grid(exp, off, psdGraph, labels = c("A", "B", "C"), ncol = 3,label_size = 30)

```

# MRS Plots 
```{r mrsPlots, echo= FALSE, message = FALSE, warning = FALSE,  fig.height=20, fig.width = 17}

MRSlong <- MRSlong %>% mutate(ageGroup = cut(age, c(0,17,23,Inf), labels = c('10-16','17-22','23-30')))

# Glu vs age 
glu <- lunaize(ggplot(data = MRSlong, 
                      aes(x = age, y = Glu_gamadj)) + 
                 geom_line(aes(group=interaction(luna,Region)), alpha = 0.2) + 
                 geom_point(aes(shape=Region, color = ageGroup), size=2.5,alpha=.8) + 
                 geom_smooth(aes(group = 1), color="black", method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.4,size=2) + 
                 scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + xlab("Age") + ylab("Glutamate") + 
  theme(text = element_text(size = 25), 
        legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5,"cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2)) +
  geom_text(
    aes(x = 33, y = 1.45, label = "*"),
    size = 15)


# GABA vs Age
gaba <- lunaize(ggplot(data = MRSlong, 
                       aes(x = age, y = GABA_gamadj)) + 
                  geom_line(aes(group=interaction(luna,Region)), alpha = 0.2) + 
                  geom_point(aes(shape=Region, color = ageGroup), size=2.5,alpha=.8) + 
                  geom_smooth(aes(group = 1), color="black", method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.4,size=2) + 
                  scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + xlab("Age") +ylab("GABA")+
  theme(text = element_text(size = 25), 
        legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5,"cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2)) 


# Ratio vs Age
ratio <- lunaize(ggplot(data = MRSlong, 
                        aes(x = age, y = Ratio_gamadj, by = luna, shape = Region, linetype = Region)) + 
                   geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                   geom_point(aes(shape=Region, color = ageGroup), size=2.5,alpha=.8) + 
                   geom_smooth(aes(group = 1), color="black", method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.4,size=2) + 
                   scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + xlab("Age") +ylab("Glu/GABA Ratio") + 
  theme(text = element_text(size = 25), 
        legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2)) 


# Imbalance vs Age
imb <- lunaize(ggplot(data = MRSlong, 
                      aes(x = age, y = sqrt(GluGABAimbalanceABS), by = luna, shape = Region, linetype = Region)) + 
                 geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                 geom_point(aes(shape=Region, color = ageGroup), size=2.5,alpha=.8) + 
                 geom_smooth(aes(group = 1), color="black", method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T), alpha=0.4, size=2) + 
                 scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + xlab("Age") + ylab("Glu GABA Asymmetry") + 
  theme(text = element_text(size = 25), legend.position = c(.8,0.89), legend.text.align = 0, plot.margin = margin(0.5,0.5,0.5,0.5, "cm"),
        aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2),legend.key.width = unit(2, "line"),legend.key=element_rect(fill="white")) + 
  geom_text(aes(x = 33.6, y = 0.35, label = "***"),size = 15) +
  scale_shape_manual(values = c(16, 17), labels = c("L DLPFC", "R DLPFC")) + scale_linetype_manual(values = c(1,2), labels = c("L DLPFC", "R DLPFC")) + guides(shape = guide_legend(title = "Region", override.aes = list(size = 4,fill=NA,alpha=0.5),title.theme = element_text(size = 25), label.theme= element_text(size = 25)),linetype = guide_legend(override.aes = list(linewidth = 1,color ="black"),text.theme = element_text(size = 10)), color="none", size = "none")

gam.model <-  mgcv::gamm(GluGABAimbalanceABS ~ s(age, k = 3) + Region , data = MRSlong, random=list(luna=~1))
summary(gam.model$gam)

plot_grid(glu, gaba, ratio,imb, labels = c("A", "B", "C","D"), ncol = 2,label_size = 40, align = "b")
```


```{r mrsPlots2, echo= FALSE, message = FALSE, warning = FALSE,  fig.height=18, fig.width = 7}

#Calculate the linear regression model
lm_model <- lm(GABA_gamadj ~ Glu_gamadj, data = MRSlong %>% filter(ageGroup == "10-16"))

# Extract the slope and intercept of the smoothed line
slope <- coef(lm_model)[2]  # Slope
intercept <- coef(lm_model)[1]  # Intercept

# Calculate the residuals from the linear regression model
residuals <- resid(lm_model)

# Calculate the standard deviation of the residuals
residual_sd <- sd(residuals)

#Glu vs GABA to illustrate imbalance
young<- lunaize(ggplot(data = MRSlong %>% filter(ageGroup == "10-16"), 
                      aes(x = Glu_gamadj, y = GABA_gamadj)) + 
                 geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                 geom_point(aes(shape=Region, color = ageGroup), size=2.5,alpha=.8) + 
                 geom_smooth(aes(group = 1), color="#E3B23C", method="lm", alpha=0.4, size=2) + 
                 scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + xlab("Glu") + ylab("GABA") + 
  theme(text = element_text(size = 25), legend.position = "none", legend.text.align = 0, plot.margin = margin(0.5,0.5,0.5,0.5, "cm"),
        aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2),legend.key.width = unit(2, "line"),legend.key=element_rect(fill="white")) +  
  geom_abline(intercept = intercept + residual_sd, slope = slope, linetype = "dashed", color = "red", size = 1) + # Add dashed line 1 SD above   
  geom_abline(intercept = intercept - residual_sd, slope = slope, linetype = "dashed", color = "red", size = 1)  # Add dashed line 1 SD below


# Calculate the linear regression model
lm_model <- lm(GABA_gamadj ~ Glu_gamadj, data = MRSlong %>% filter(ageGroup == "17-22"))

# Extract the slope and intercept of the smoothed line
slope <- coef(lm_model)[2]  # Slope
intercept <- coef(lm_model)[1]  # Intercept

# Calculate the residuals from the linear regression model
residuals <- resid(lm_model)

# Calculate the standard deviation of the residuals
residual_sd <- sd(residuals)

middle<- lunaize(ggplot(data = MRSlong %>% filter(ageGroup == "17-22"), 
                      aes(x = Glu_gamadj, y = GABA_gamadj)) + 
                 geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                 geom_point(aes(shape=Region), size =2.5,alpha=.8,color="plum4") + 
                 geom_smooth(aes(group = 1), color="plum4", method="lm", alpha=0.4, size=2)) + xlab("Glu") + ylab("GABA") + 
  theme(text = element_text(size = 25), legend.position = "none", legend.text.align = 0, plot.margin = margin(0.5,0.5,0.5,0.5, "cm"),
        aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2),legend.key.width = unit(2, "line"),legend.key=element_rect(fill="white"))+  
  geom_abline(intercept = intercept + residual_sd, slope = slope, linetype = "dashed", color = "red", size = 1) + # Add dashed line 1 SD above   
  geom_abline(intercept = intercept - residual_sd, slope = slope, linetype = "dashed", color = "red", size = 1)  # Add dashed line 1 SD below


#Calculate the linear regression model
lm_model <- lm(GABA_gamadj ~ Glu_gamadj, data = MRSlong %>% filter(ageGroup == "23-30"))

# Extract the slope and intercept of the smoothed line
slope <- coef(lm_model)[2]  # Slope
intercept <- coef(lm_model)[1]  # Intercept

# Calculate the residuals from the linear regression model
residuals <- resid(lm_model)

# Calculate the standard deviation of the residuals
residual_sd <- sd(residuals)



old <- lunaize(ggplot(data = MRSlong %>% filter(ageGroup == "23-30"), 
                      aes(x = Glu_gamadj, y = GABA_gamadj)) + 
                 geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                 geom_point(aes(shape=Region), color = "#2E041F", size =2.5,alpha=.8) + 
                 geom_smooth(aes(group = 1), color="#2E041F", method="lm", alpha=0.4, size=2)) + xlab("Glu") + ylab("GABA") + 
  theme(text = element_text(size = 25), legend.position = "none", legend.text.align = 0, plot.margin = margin(0.5,0.5,0.5,0.5, "cm"),
        aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2),legend.key.width = unit(2, "line"),legend.key=element_rect(fill="white"))+  
  geom_abline(intercept = intercept + residual_sd, slope = slope, linetype = "dashed", color = "red", size = 1) + # Add dashed line 1 SD above   
  geom_abline(intercept = intercept - residual_sd, slope = slope, linetype = "dashed", color = "red", size = 1)  # Add dashed line 1 SD below



plot_grid(young, middle, old, labels = c("E", "", ""), ncol = 1,label_size = 40)

```

# MRS FOOOF Plots
```{r mrsFooof, echo= FALSE, message = FALSE, warning = FALSE,fig.height=11, fig.width = 19}
fooofMRS <- fooofMRS %>% mutate(ageGroup = cut(age, c(0,17,23,Inf), labels = c('10-16','17-22','23-30')))


imbExp <- lunaize(ggplot(data = fooofMRS, 
                         aes(x = sqrt(GluGABAimbalanceABS), y = Exponent, by = luna, color = ageGroup,shape=Region)) + 
                    geom_line(aes(group=interaction(luna,Region, Condition)), alpha = 0.2) + 
                    geom_point(aes(shape=Region, color = ageGroup), size =2.5,alpha=.8) + 
                    geom_smooth(aes(group = 1), method="lm",alpha=.4,size=2, color="black")) + 
  scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black")) + 
  xlab("Glu GABA Asymmetry") + ylab("Exponent") + ylim(0.7, 2) +
  theme(text = element_text(size = 25), legend.position = c(0.69,0.11), legend.text.align = 0, plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2))+
  geom_text(aes(y = 1.5, x = 0.97, label = "***"), size = 10, color="black") +
  annotate("text", x = 0.86, y = 0.9, label = "10-16", size = 6, colour = "#E3B23C", hjust =0) +
  annotate("text", x = 0.86, y = 0.8, label = "17-22", size = 6, colour = "plum4",hjust=0) +
  annotate("text", x = 0.86, y = 0.7, label = "23+", size = 6, colour = "#2E041F",hjust=0) +
  scale_shape_manual(values = c(16, 17), labels = c("L DLPFC", "R DLPFC")) + guides(shape = guide_legend(title = "Region", override.aes = list(size = 3),title.theme = element_text(size = 15), label.theme= element_text(size = 15)), color="none",size ="none")

imbOff <- lunaize(ggplot(data = fooofMRS, 
                         aes(y = Offset, x = sqrt(GluGABAimbalanceABS), by =luna, color = ageGroup)) + 
                    geom_line(aes(group=interaction(luna,Region, Condition)), alpha = 0.4) + 
                    geom_point(aes(shape=Region, color = ageGroup),size = 2.5,alpha=0.8) + 
                    geom_smooth(aes(group = 1, alpha = 0.01), method="lm",alpha=.4,size=2, color="black")) + 
  scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black")) + 
  xlab("Glu GABA Asymmetry") + ylab("Offset") + ylim(-0.04, 2) +
  theme(text = element_text(size = 25), legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5,  "cm"), 
        aspect.ratio = 1,axis.title.y = element_text(vjust = 2),  axis.title.x = element_text(vjust = -2))+
  scale_shape_manual(values = c(16, 17), labels = c("L DLPFC", "R DLPFC"))+
  geom_text(aes(y = 1.1, x = 0.97, label = "**"), size = 10, color="black") 

gluExp <- lunaize(ggplot(data = fooofMRS , 
                         aes(y = Exponent, x = Glu_gamadj, by = luna, color = ageGroup))+ 
                    geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.4) +
                    geom_point(aes(shape=Region, color = ageGroup),size = 2.5,alpha=0.8) + 
                    geom_smooth(aes(group = 1), method="lm", alpha = 0.4, color="black", size=2) + 
                    scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  xlab("Glutamate") + ylab("Exponent") + ylim(0.7, 2) +
  theme(text = element_text(size = 25),  legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5,  "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2),    axis.title.x = element_text(vjust = -2))+
  geom_text(aes(y = 1.5, x = 2.5, label = "*"), size = 10 , color="black")+
  scale_shape_manual(values = c(16, 17), labels = c("L DLPFC", "R DLPFC")) 

gluOff <- lunaize(ggplot(data = fooofMRS, 
                         aes(y = Offset, x = Glu_gamadj, by = luna, color = ageGroup))+ 
                    geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.4) + 
                    geom_point(aes(shape =Region, color = ageGroup), size =2.5,alpha=0.8) + 
                    geom_smooth(aes(group = 1), method="lm", alpha = 0.4, color="black", size=2) + 
                    scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  xlab("Glutamate") + ylab("Offset") + ylim(-0.04, 2) +
  theme(text = element_text(size = 25),  legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5,  "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2),  axis.title.x = element_text(vjust = -2)) +
  scale_shape_manual(values = c(16, 17), labels = c("L DLPFC", "R DLPFC"))

gabaExp <- lunaize(ggplot(data = fooofMRS, 
                          aes(y = Exponent, x = GABA_gamadj, by = luna, color = ageGroup))+ 
                     geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.4) + 
                     geom_point(aes(shape=Region, color = ageGroup), size =2.5,alpha=0.8) + 
                     geom_smooth(aes(group = 1), method="lm", alpha = 0.4, color="black", size=2) + 
                     scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  xlab("GABA") + ylab("Exponent") + ylim(0.7, 2) +
  theme(text = element_text(size = 25),  legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))+
  scale_shape_manual(values = c(16, 17), labels = c("L DLPFC", "R DLPFC"))

gabaOff <- lunaize(ggplot(data = fooofMRS , 
                          aes(y = Offset, x = GABA_gamadj, by = luna, color = ageGroup))+ 
                     geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.4) + 
                     geom_point(aes(shape=Region, color = ageGroup), size = 2.5,alpha=0.8) + 
                     geom_smooth(aes(group = 1), method="lm", alpha = 0.4, color="black",size=2) + 
                     scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  xlab("GABA") + ylab("Offset") + ylim(-0.04, 2) +
  theme(text = element_text(size = 25), legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5,  "cm"), 
        aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))+
  scale_shape_manual(values = c(16, 17), labels = c("L DLPFC", "R DLPFC"))

plot_grid(imbExp, gluExp, gabaExp,  imbOff, gluOff, gabaOff, labels = c("A", "B", "C","D", "E", "F"), ncol = 3,nrow = 2,label_size = 30, align = "b")

```

# Behavior vs FOOOF
```{r behavFoooF, echo= FALSE, message = FALSE, warning = FALSE, fig.width=10, fig.height=11}
fooofMRSbehavior <- fooofMRSbehavior %>% mutate(ageGroup = cut(age, c(0,17,23,Inf), labels = c('10-16','17-22','23-30')))

### Latency vs Exponent ----

latExp <- lunaize(ggplot(data = fooofMRSbehavior , 
                         aes(x = Exponent, y = mgsLatency, by = luna, color = ageGroup))+ 
                    geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
                    geom_point(aes(shape=Region, color = ageGroup), size = 2.5,alpha=0.8)  + 
                    geom_smooth(aes(group = 1), method="lm", alpha = 0.4, color = "black", size=2) + 
                     scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  ylab("Latency") + xlab("Exponent")+
  theme(text = element_text(size = 25), legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2)) +
   annotate("text", x = 0.6, y = .5, label = "10-16", size = 7, colour = "#E3B23C", hjust =0) +
  annotate("text", x = 0.6, y = 0.47, label = "17-22", size = 7, colour = "plum4",hjust=0) +
  annotate("text", x = 0.6, y = 0.44, label = "23+", size = 7, colour = "#2E041F",hjust=0)

###  Latency  vs Offset ----

latOff <- lunaize(ggplot(data = fooofMRSbehavior, 
                         aes(x = Offset, y = mgsLatency, by = luna, color = ageGroup))+ 
                    geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
                    geom_point(aes(shape=Region, color = ageGroup), size = 2.5,alpha=0.8)  + 
                    geom_smooth(aes(group = 1), method="lm", alpha = 0.4, color = "black", size=2) + 
                     scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  ylab("Latency") + xlab("Offset")+
  theme(text = element_text(size = 25),
        legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2),
        axis.title.x = element_text(vjust = -2)) +
  geom_text(aes(x = 2, y = 0.355, label = "**"), size = 10, color="black" ) 

### Spatial Span Max vs Exponent ----

sspExp <- lunaize(ggplot(data = fooofMRSbehavior  , 
                         aes(x = Exponent, y = SSP_maxSpan, by = luna, color = ageGroup))+ 
                    geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
                    geom_point(aes(shape=Region, color = ageGroup), size = 2.5,alpha=0.8)  + 
                    geom_smooth(aes(group = 1), method="lm", alpha = 0.4,color = "black", size=2) + 
                    scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  ylab("Span Max") + xlab("Exponent")+theme(text = element_text(size = 25), 
                                            legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
                                            axis.title.x = element_text(vjust = -2)) +
  geom_text(aes(x = 2.1, y = 6.5, label = "**"), size = 10 , color="black") 


### Spatial Span Max vs Offset ----

sspOffset <- lunaize(ggplot(data = fooofMRSbehavior  , 
                            aes(x = Offset, y = SSP_maxSpan, by = luna, color = ageGroup))+ 
                       geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
                       geom_point(aes(shape=Region, color = ageGroup), size = 2.5,alpha=0.8) + 
                       geom_smooth(aes(group = 1), color = "black",method="lm", alpha = 0.4, size=2) + 
                      scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  ylab("Span Max") + xlab("Offset") +
  theme(text = element_text(size = 25),legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), 
        aspect.ratio = 1,axis.title.y = element_text(vjust = 2),axis.title.x = element_text(vjust = -2)) +
  geom_text(aes(x = 2, y = 6.5, label = "**"), size = 10, color="black") 

plot_grid(latExp, latOff, sspExp,sspOffset, labels = c("A", "B", "C","D"), ncol = 2,label_size = 30, align = "b")

```

# Behavior vs MRS
```{r behavMRS, echo= FALSE, message = FALSE, warning = FALSE, fig.width=19, fig.height=8}
### Latency vs Imbalance ----

latImb <- lunaize(ggplot(data = fooofMRSbehavior , 
                         aes(x = sqrt(GluGABAimbalanceABS), y = mgsLatency, by = luna, color = ageGroup))+ 
                    geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
                    geom_point(aes(shape=Region, color = ageGroup), size = 2.5,alpha=0.8) + 
                    geom_smooth(aes(group = 1), method="lm", alpha = 0.4, color="black", size=2) + 
                    scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  ylab("Latency") + xlab("Glu GABA Asymmetry")+
  theme(text = element_text(size = 25), legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), 
        aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))

latGlu <- lunaize(ggplot(data = fooofMRSbehavior , 
                         aes(x = Glu_gamadj, y = mgsLatency, by = luna, color = ageGroup))+ 
                    geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
                   geom_point(aes(shape=Region, color = ageGroup), size = 2.5,alpha=0.8) + 
                    geom_smooth(aes(group = 1), method="lm", alpha = 0.4, color="black", size=2) + 
                    scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  ylab("Latency") + xlab("Glutamate") +
  theme(text = element_text(size = 25), legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2)) +
  geom_text(aes(x = 2.56, y = 0.368, label = "***"), size = 10 , color="black") 

latGABA <- lunaize(ggplot(data = fooofMRSbehavior , 
                          aes(x = GABA_gamadj, y = mgsLatency, by = luna, color = ageGroup))+ 
                     geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
                     geom_point(aes(shape=Region, color = ageGroup), size = 2.5,alpha=0.8) + 
                     geom_smooth(aes(group = 1), method="lm", alpha = 0.4, color="black", size=2) + 
                     scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + 
  ylab("Latency") + xlab("GABA")+theme(text = element_text(size = 25), 
                                       legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2)) +
  annotate("text", x = 0.7, y = .55, label = "10-16", size = 7, colour = "#E3B23C", hjust =0) +
  annotate("text", x = 0.7, y = 0.52, label = "17-22", size = 7, colour = "plum4",hjust=0) +
  annotate("text", x = 0.7, y = 0.49, label = "23+", size = 7, colour = "#2E041F",hjust=0)

plot_grid(latImb, latGlu, latGABA, labels = c("A", "B", "C"), ncol = 3, label_size = 30, align = "b")


```

# Supplement
```{r supp, echo= FALSE, message = FALSE, warning = FALSE, fig.height=10, fig.width = 35}
MRSlong <- MRSlong %>% mutate(ageGroup = cut(age, c(0,17,23,Inf), labels = c('10-16','17-22','23-30')))

# looking at main effects of hemisphere
# Glu vs age 
glu <- lunaize(ggplot(data = MRSlong, 
                      aes(x = age, y = Glu_gamadj, linetype = Region)) + 
                 geom_line(aes(group=interaction(luna,Region)), alpha = 0.2) + 
                 geom_point(aes(shape=Region, color = ageGroup), size=2.5,alpha=.8) + 
                 geom_smooth(aes(group = Region), color="black", method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.4,size=2) + 
                 scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + xlab("Age") + ylab("Glutamate") + 
  theme(text = element_text(size = 25), 
        legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5,"cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2)) +
  geom_text(
    aes(x = 33.2, y = 1.38, label = "**"),
    size = 15)


# GABA vs Age
gaba <- lunaize(ggplot(data = MRSlong, 
                       aes(x = age, y = GABA_gamadj, linetype=Region)) + 
                  geom_line(aes(group=interaction(luna,Region)), alpha = 0.2) + 
                  geom_point(aes(shape=Region, color = ageGroup), size=2.5,alpha=.8) + 
                  geom_smooth(aes(group = Region), color="black", method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.4,size=2) + 
                  scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + xlab("Age") +ylab("GABA")+
  theme(text = element_text(size = 25), 
        legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5,"cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2)) 


# Ratio vs Age
ratio <- lunaize(ggplot(data = MRSlong, 
                        aes(x = age, y = Ratio_gamadj, by = luna, shape = Region, linetype = Region)) + 
                   geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                   geom_point(aes(shape=Region, color = ageGroup), size=2.5,alpha=.8) + 
                   geom_smooth(aes(group = Region), color="black", method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.4,size=2) + 
                   scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + xlab("Age") +ylab("Glu/GABA Ratio") + 
  theme(text = element_text(size = 25), 
        legend.position = "none", plot.margin = margin(0.5,0.5,0.5,0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2)) +
  geom_text(
    aes(x = 33.2, y = 3.7, label = "*"),
    size = 15)


# Imbalance vs Age
imb <- lunaize(ggplot(data = MRSlong, 
                      aes(x = age, y = sqrt(GluGABAimbalanceABS), by = luna, shape = Region, linetype = Region)) + 
                 geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                 geom_point(aes(shape=Region, color = ageGroup), size=2.5,alpha=.8) + 
                 geom_smooth(aes(group = Region), color="black", method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T), alpha=0.4, size=2) + 
                 scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) + xlab("Age") + ylab("Glu GABA Asymmetry") + 
  theme(text = element_text(size = 25), legend.position = c(.8,0.89), legend.text.align = 0, plot.margin = margin(0.5,0.5,0.5,0.5, "cm"),
        aspect.ratio = 1,axis.title.y = element_text(vjust = 2), 
        axis.title.x = element_text(vjust = -2),legend.key.width = unit(2, "line"),legend.key=element_rect(fill="white")) + 
  geom_text(aes(x = 33.6, y = 0.35, label = "***"),size = 15) +
  scale_shape_manual(values = c(16, 17), labels = c("L DLPFC", "R DLPFC")) + scale_linetype_manual(values = c(1,2), labels = c("L DLPFC", "R DLPFC")) + guides(shape = guide_legend(title = "Region", override.aes = list(size = 4,fill=NA,alpha=0.5),title.theme = element_text(size = 25), label.theme= element_text(size = 25)),linetype = guide_legend(override.aes = list(linewidth = 1,color ="black"),text.theme = element_text(size = 10)), color="none", size = "none")


plot_grid(glu, gaba, ratio,imb, labels = c("A", "B", "C","D"), ncol = 4,label_size = 40, align = "b")
```

```{r supp2, echo= FALSE, message = FALSE, warning = FALSE, fig.width=100, fig.height=100}

### Accuracy vs Exponent ----

accExp <- lunaize(ggplot(data = fooofMRSbehavior,
               aes(y = absBestError, x = Exponent, by = luna, color = ageGroup)) +
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Accuracy") + xlab("Exponent")+
  theme(text = element_text(size = 90),legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))+
  annotate("text", x = 0.65, y = 5, label = "10-16", size = 30, colour = "#E3B23C", hjust =0) +
  annotate("text", x = 0.65, y = 4.6, label = "17-22", size = 30, colour = "plum4",hjust=0) +
  annotate("text", x = 0.65, y = 4.2, label = "23+", size = 30, colour = "#2E041F",hjust=0) 




###  Accuracy vs Offset ----

accOff <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = Offset, y = absBestError, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Accuracy") + xlab("Offset")+ theme(text = element_text(size = 90),legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))


### Accuracy vs Glu ----

accGlu <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = Glu_gamadj, y = absBestError, by = luna, color = ageGroup)) +
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Accuracy") + xlab("Glu")+ theme(text = element_text(size = 90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))

### Accuracy vs GABA ----

accGABA <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = GABA_gamadj, y = absBestError, by = luna, color = ageGroup)) +
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Accuracy") + xlab(" GABA ")+ theme(text = element_text(size=90))+
  theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2)) +
  geom_text(aes(x = 0.88, y = 3, label = "*"), size = 10 )


### Accuracy vs Imbalance ----

accImb <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = sqrt(GluGABAimbalanceABS), y = absBestError, by = luna, color = ageGroup)) +
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Accuracy") + xlab("Glu GABA Asymmetry")+
  theme(text = element_text(size=90)) +
  theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))


### Accuracy Var vs Exponent ----

accvExp <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = Exponent, y = absBestError_sd, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Accuracy Var") + xlab("Exponent")+ theme(text = element_text(size=90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))

### Accuracy Var vs Glu ----

accvGlu <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = Glu_gamadj, y = absBestError_sd, by = luna, color = ageGroup)) +
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Accuracy Var") + xlab("Glu")+ theme(text = element_text(size=90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))

### Accuracy Var vs GABA ----

accvGABA <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = GABA_gamadj, y = absBestError_sd, by = luna, color = ageGroup)) +
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Accuracy Var") + xlab(" GABA ")+ theme(text = element_text(size=90))+
  theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))+
  geom_text(aes(x = .89, y = 3.12, label = "**"), size = 10 )

### Accuracy Var vs Offset ----

accvOff <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = Offset, y = absBestError_sd, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Accuracy Var") + xlab("Offset")+ theme(text = element_text(size=90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))

###  Accuracy Var  vs Imbalance ----

accvImb <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = GluGABAimbalanceABS, y = absBestError_sd, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Accuracy Var") + xlab("Glu GABA Asymmetry")+ theme(text = element_text(size=90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))

### Latency Var  vs Exponent ----

latvExp <- lunaize(ggplot(data = fooofMRSbehavior,
               aes(x = Exponent, y = mgsLatency_sd, by = luna, color = ageGroup)) +
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group =1), method="lm", alpha = 0.8)) +
  scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black")) +
  ylab("Latency Var") + xlab("Exponent")+ theme(text = element_text(size=90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))

###  Latency Var vs Offset ----
latvOff <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = Offset, y = mgsLatency_sd, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group =1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Latency Var") + xlab("Offset")+ theme(text = element_text(size=90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))

###  Latency Var vs Glu ----
latvGlu <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = Glu_gamadj, y = mgsLatency_sd, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group =1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Latency Var") + xlab("Glu")+ theme(text = element_text(size=90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))


###  Latency Var vs GABA ----
latvGABA <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = GABA_gamadj, y = mgsLatency_sd, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group =1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Latency Var") + xlab("GABA")+ theme(text = element_text(size=90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))


### Latency Var vs Imbalance ----

latvImb <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = sqrt(GluGABAimbalanceABS), y = mgsLatency_sd, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Latency Var") + xlab("Glu GABA Asymmetry")+ theme(text = element_text(size=90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))



### Spatial Span Max vs Glu ----

sspGlu <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = Glu_gamadj, y = SSP_maxSpan, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Span Max") + xlab("Glu")+ theme(text = element_text(size=90))+
  theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))

### Spatial Span Max vs GABA ----

sspGABA <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = GABA_gamadj, y = SSP_maxSpan, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Span Max") + xlab("GABA") +
  theme(text = element_text(size=90))+ theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))


### Spatial Span Max vs Imbalance ----

sspImb <- lunaize(ggplot(data = fooofMRSbehavior  ,
               aes(x = sqrt(GluGABAimbalanceABS), y = SSP_maxSpan, by = luna, color = ageGroup))+
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) +
          geom_point(alpha=0.8) +
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) +
          scale_color_manual(values=c("#E3B23C", "plum4", "#2E041F","black"))) +
  ylab("Span Max") + xlab("Glu GABA Asymmetry")+ theme(text = element_text(size=90))+
  theme(legend.position='none',plot.margin = margin(1.0,1.0,1.0,1.0, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 2), axis.title.x = element_text(vjust = -2))


plot_grid(accExp, accOff, accGlu, accGABA, accImb, accvExp, accvOff, accvGlu, accvGABA, accvImb, latvExp, latvOff, latvGlu, latvGABA, latvImb, sspGlu, sspGABA, sspImb, labels = c("A", "B", "C", "D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R"), ncol = 5, label_size = 150, align = "b")

```

