---
title: "Fooof MRS Paper"
author: "Shane McKeon"
date: "2023-08-31"
geometry: margin = 1in
output:
  pdf_document: 
    toc: yes
    toc_depth: 4
    fig_caption: yes
  latex_engine: xelatex
---

```{r load-libraries, message=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, dev='png', dpi=150, fig.height=45, fig.width = 100, fig.path='/Users/shanemckeon/Library/CloudStorage/OneDrive-UniversityofPittsburgh/Lab/Projects/FOOOF/paperFigs/')
```


```{r, echo= FALSE, message = FALSE, warning = FALSE}

library(LNCDR)
library(data.table)
library(dplyr)
require(knitr)
library(ggplot2)
library(e1071)
library(caret)
library(ggplot2)
library(readxl)
library(Hmisc)
library(lmerTest)
library(corrplot)
library(RColorBrewer)
library(data.table)
library(cowplot)
library(mgcv)

```

```{r, echo= FALSE, message = FALSE, warning = FALSE}

fooofMRSbehavior <- read.csv("/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Results/FOOOF/allSubjectsDLPFCfooofMRSBehaviorMeasures_20230822.csv")
fooofLong <- read.csv("/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Results/FOOOF/Results/allSubjectsDLPFCfooofMeasures_20230613.csv")
MRSlong <- read.csv("/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Results/FOOOF/Results/allSubjectsDLPFCMRSMeasures_20230613.csv")
fooofMRS<- read.csv("/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Results/FOOOF/allSubjectsDLPFCfooofMRSMeasures_20230822.csv")
behav <- read.csv("/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Results/FOOOF/Results/allSubjectsBehavior.csv")


```

# FOOOF Plots 
```{r fooofPlots, echo= FALSE, message = FALSE, warning = FALSE, fig.height=40, fig.width = 100}

# Exponent vs age
exp <- lunaize(ggplot(data = fooofLong, 
                      aes(x = age, y = Exponent)) + 
                 geom_line(aes(group=interaction(luna,Region,Condition), linetype = Condition, shape =Region), alpha = 0.4) + 
                 geom_point(aes(shape=Region),alpha=.8) + 
                 geom_smooth(aes(group = 1), method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.8,size=1)) + xlab("Age") + ylab("Exponent") +
  geom_text(
    aes(x = 34.5, y = 1.2, label = "***"),
    size = 35) +
  theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm") , aspect.ratio = 1, axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))


# Offset vs age
off <- lunaize(ggplot(data = fooofLong, 
                      aes(x = age, y = Offset)) + 
                 geom_line(aes(group=interaction(luna,Region,Condition), linetype = Condition, shape =Region), alpha = 0.4) + 
                 geom_point(aes(shape=Region),alpha=.8) + 
                 geom_smooth(aes(group = 1), method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.8,size=1)) + xlab("Age") + ylab("Offset") + 
  geom_text(aes(x = 34.5, y = .6, label = "***"), size = 35) +
  theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))

# exponent vs offset

expOff <- lunaize(ggplot(data = fooofLong, 
                         aes(x = Offset, y = Exponent)) + 
                    geom_line(aes(group=interaction(luna,Region,Condition), linetype = Condition, shape =Region, color = Region), alpha = 0.4) + 
                    geom_point(aes(shape=Region, color = Region),alpha=.8) + 
                    geom_smooth(aes(group = 1), color = 'black',method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.8,size=1)) + 
  scale_color_manual(values=c("gold3", "blue4")) + 
  xlab("Offset") + ylab("Exponent") +
  annotate("text", x = 1, y = 0.2, label = expression(rho ~" = 0.75, p < 2.2e-16"), size = 35, hjust =0) +
  annotate("text", x = 0, y = 2, label = "Adolescence", size = 35, colour = "gold3", hjust =0) +
  annotate("text", x = 0, y = 1.9, label = "Adult", size = 35, colour = "blue4",hjust=0) +
  theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2)) 


plot_grid(exp, off, expOff, labels = c("A", "B", "C"), ncol = 3,label_size = 150)

#ggsave(filename = "/Volumes/Hera/Projects/7TBrainMech/scripts/eeg/Shane/Results/FOOOF/Results/foofplot.png", plot = fooofPlots)

```

# MRS Plots 
```{r mrsPlots, echo= FALSE, message = FALSE, warning = FALSE, fig.height=35, fig.width = 100}

# Glu vs age 
glu <- lunaize(ggplot(data = MRSlong, 
                      aes(x = age, y = Glu_gamadj, by = luna, shape = Region, linetype = Region)) + 
                 geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                 geom_point(alpha=.8) + 
                 geom_smooth(aes(group = 1), method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.8,size=1) + 
                 scale_color_manual(values=c("gold3", "blue4"))) + xlab("Age") + ylab("Glutamate") + 
  theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2)) +
  geom_text(
    aes(x = 33, y = 1.35, label = "*"),
    size = 35)



# GABA vs Age
gaba <- lunaize(ggplot(data = MRSlong, 
                       aes(x = age, y = GABA_gamadj, by = luna, shape = Region, linetype = Region)) + 
                  geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                  geom_point(alpha=.8) + 
                  geom_smooth(aes(group = 1), method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.8,size=1) + 
                  scale_color_manual(values=c("gold3", "blue4"))) + xlab("Age") +ylab("GABA")+
  theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2)) 


# Ratio vs Age
ratio <- lunaize(ggplot(data = MRSlong, 
                        aes(x = age, y = Ratio_gamadj, by = luna, shape = Region, linetype = Region)) + 
                   geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                   geom_point(alpha=.8) + 
                   geom_smooth(aes(group = 1), method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T),alpha=0.8,size=1) + 
                   scale_color_manual(values=c("gold3", "blue4"))) + xlab("Age") +ylab("Glu/GABA Ratio") + 
  theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2)) 


# Imbalance vs Age
imb <- lunaize(ggplot(data = MRSlong, 
                      aes(x = age, y = GluGABAimbalanceABS, by = luna, shape = Region, linetype = Region)) + 
                 geom_line(aes(group=interaction(luna,Region)), alpha = 0.4) + 
                 geom_point(alpha=.8) + 
                 geom_smooth(aes(group = 1), method=mgcv::"gam", formula = y ~ s(x, k = 3, fx = T), alpha=0.8, size=1) + 
                 scale_color_manual(values=c("gold3", "blue4"))) + xlab("Age") +ylab("Glu GABA Asymmetry") + 
  theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2)) + 
  geom_text(aes(x = 33, y = 0.15, label = "*"),
    size = 35 ) 


plot_grid(glu, gaba, ratio,imb, labels = c("A", "B", "C","D"), ncol = 4,label_size = 150, align = "b")



```

# MRS FOOOF Plots
```{r mrsFooof, echo= FALSE, message = FALSE, warning = FALSE,fig.height=65, fig.width = 35}
imbExp <- lunaize(ggplot(data = fooofMRS, 
               aes(y = GluGABAimbalanceABS, x = Exponent, by =luna, color = ageGroup)) + 
          geom_line(aes(group=interaction(luna,Region, Condition)), alpha = 0.4) + geom_point(aes(shape=Region),alpha=.5) + 
          geom_smooth(aes(group = 1), method="lm",formula = y ~ poly(x,2),alpha=.8,size=1)) + 
  scale_color_manual(values=c("gold3", "blue4")) + 
  ylab("Glu GABA Asymmetry") + xlab("Exponent")+ theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))+
  geom_text(aes(x = 2.03, y = 0.21, label = "*"), size = 35 ) 


imbOff <- lunaize(ggplot(data = fooofMRS, 
               aes(x = Offset, y = GluGABAimbalanceABS, by =luna, color = ageGroup)) + 
          geom_line(aes(group=interaction(luna,Region, Condition)), alpha = 0.4) + 
          geom_point(aes(shape=Region),alpha=.5) + 
          geom_smooth(aes(group = 1, alpha = 0.01), method="lm",alpha=.8,size=1)) + 
  scale_color_manual(values=c("gold3", "blue4")) + 
  ylab("Glu GABA Asymmetry") + xlab("Offset")+ theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))

gluExp <- lunaize(ggplot(data = fooofMRS , 
               aes(x = Exponent, y = Glu_gamadj, by = luna, color = ageGroup))+ 
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.4) +
          geom_point(aes(shape=Region),alpha=.5) + geom_smooth(aes(group = 1), method="lm", alpha = 0.8) + 
          scale_color_manual(values=c("gold3", "blue4"))) + 
  ylab("Glutamate") + xlab("Exponent") + theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))+
  geom_text(aes(x = 2.03, y = 1.54, label = "*"), size = 35 ) 

gluOff <- lunaize(ggplot(data = fooofMRS, 
               aes(x = Offset, y = Glu_gamadj, by = luna, color = ageGroup))+ 
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.4) + 
          geom_point(aes(shape =Region),alpha=.5) + geom_smooth(aes(group = 1), method="lm", alpha = 0.8) + 
          scale_color_manual(values=c("gold3", "blue4"))) + 
  ylab("Glutamte") + xlab("Offset") + theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2)) +
  geom_text(aes(x = 1.9, y = 1.53, label = "*"), size = 35 ) 

gabaExp <- lunaize(ggplot(data = fooofMRS , 
               aes(x = Exponent, y = GABA_gamadj, by = luna, color = ageGroup))+ 
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.4) + 
          geom_point(aes(shape=Region),alpha=.5) + geom_smooth(aes(group = 1), method="lm", alpha = 0.8) + 
          scale_color_manual(values=c("gold3", "blue4"))) + 
  ylab("GABA") + xlab("Exponent") + theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))

gabaOff <- lunaize(ggplot(data = fooofMRS , 
               aes(x = Offset, y = GABA_gamadj, by = luna, color = ageGroup))+ 
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.4) + 
          geom_point(aes(shape=Region),alpha=.5) + geom_smooth(aes(group = 1), method="lm", alpha = 0.8) + 
          scale_color_manual(values=c("gold3", "blue4"))) + 
  ylab("GABA") + xlab("Offset")+theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))

plot_grid(imbExp, imbOff, gluExp, gluOff, gabaExp, gabaOff, labels = c("A", "B", "C","D", "E", "F"), ncol = 2,nrow = 3,label_size = 150, align = "b")

```

# Behavior vs FOOOF and MRS
```{r, echo= FALSE, message = FALSE, warning = FALSE, fig.width=60, fig.height=23}
### Latency vs Exponent ----

latExp <- lunaize(ggplot(data = fooofMRSbehavior , 
               aes(x = Exponent, y = mgsLatency, by = luna, color = ageGroup))+ 
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
          geom_point(alpha=.5) + 
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) + 
          scale_color_manual(values=c("gold3", "blue4"))) + 
  ylab("Latency") + xlab("Exponent")+theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))

###  Latency  vs Offset ----

latOff <- lunaize(ggplot(data = fooofMRSbehavior, 
               aes(x = Offset, y = mgsLatency, by = luna, color = ageGroup))+ 
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
          geom_point(alpha=.5) + 
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) + 
          scale_color_manual(values=c("gold3", "blue4"))) + 
  ylab("Latency") + xlab("Offset")+theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))

### Spatial Span Max vs Exponent ----

sspExp <- lunaize(ggplot(data = fooofMRSbehavior  , 
               aes(x = Exponent, y = SSP_maxSpan, by = luna, color = ageGroup))+ 
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
          geom_point(alpha=.5) + 
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) + 
          scale_color_manual(values=c("gold3", "blue4"))) + 
  ylab("Span Max") + xlab("Exponent")+theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))



### Spatial Span Max vs Offset ----

sspOffset <- lunaize(ggplot(data = fooofMRSbehavior  , 
               aes(x = Offset, y = SSP_maxSpan, by = luna, color = ageGroup))+ 
          geom_line(aes(group=interaction(luna,Region,Condition)), alpha = 0.2) + 
          geom_point(alpha=.5) + 
          geom_smooth(aes(group = 1), method="lm", alpha = 0.8) + 
          scale_color_manual(values=c("gold3", "blue4"))) + 
  ylab("Span Max") + xlab("Offset")+theme(text = element_text(size = 90), 
        legend.position = "none", plot.margin = margin(0.5, 0.5, .5, 0.5, "cm"), aspect.ratio = 1,axis.title.y = element_text(vjust = 1.5), 
        axis.title.x = element_text(vjust = -2))

plot_grid(latExp, latOff, sspExp,sspOffset, labels = c("A", "B", "C","D"), ncol = 4,label_size = 150, align = "b")

```


```{r, echo= FALSE, message = FALSE, warning = FALSE}

```