---
title: "Spectral Events Individual Channel Analysis"
author: "Shane McKeon"
date: "11/16/2020"
geometry: margin = 1in
output:
  pdf_document:  
    toc: true
    toc_depth: 4    
    fig_caption: yes
  latex_engine: xelatex

  html_document:
    df_print: paged
    code_folding: hide 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev='png', dpi=150, fig.width = 6, fig.height=6, fig.align = 'left', fig.margin = TRUE)
```


```{r load-libraries, message=FALSE}
```


```{r, echo= FALSE, message = FALSE, warning = FALSE}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, ggplot2,lme4, multcomp, tidyr, tidyverse,wesanderson, reshape2, corrplot, ggExtra, cowplot, ggsci, mgcv, ggpointdensity, devtools, ggpubr, itsadug, useful, rmarkdown, tinytex, gratia, gamm4, car, GGally, CCA)

#devtools::install_github('LabneuroCogDevel/LNCDR')
#library(devtools)
#devtools::install_github("strengejacke/sjPlot")
library(LNCDR)
library(data.table)
require(dplyr)
library(factoextra)
library(tidyverse)
require(knitr)
library(ggplot2)
library(e1071)
library(caret)

```

```{r  echo=FALSE, message=FALSE, warning=FALSE, cashe = FALSE, include = TRUE}

sys.source("H:/Projects/7TBrainMech/scripts/eeg/Shane/Rscripts/01.PrepData.R", envir = knitr::knit_global(), chdir = TRUE)

alldf <- DelayOnly_IndividualChannels_TrialLevel()
alldata <- alldf$alldata

```

# Individual Channel Analysis 
## DLPFC
```{r  echo=FALSE, message=FALSE, warning=FALSE, include = TRUE}
sys.source("H:/Projects/7TBrainMech/scripts/eeg/Shane/Rscripts/08.IndividualChannelData.R", envir = knitr::knit_global(), chdir = TRUE)
```

```{r  echo=FALSE, message=FALSE, warning=FALSE, include = TRUE}
DLPFC_analysis()
```

## Frontal Cortex 
```{r  echo=FALSE, message=FALSE, warning=FALSE, include = TRUE}
FrontalCortex_Analysis()
```

## Parietal Cortex 
```{r  echo=FALSE, message=FALSE, warning=FALSE, include = TRUE}
ParietalCortex_Analysis()
```

## Occipital Cortex 
```{r  echo=FALSE, message=FALSE, warning=FALSE, include = TRUE}
OccipitalCortex_Analysis()
```


## Central Cortex 
```{r  echo=FALSE, message=FALSE, warning=FALSE, include = TRUE}
CentralCortex_Analysis()
```


## Whole Brain 
```{r  echo=FALSE, message=FALSE, warning=FALSE, include = TRUE}
WholeCortex_Analysis()
```

